-- Gradebook column groups: make "group" a row instead of a slug-prefix heuristic.
--
-- Until now, grouping was computed in the browser on every render (groupedColumns
-- memo in manage/gradebook/gradebookTable.tsx) by splitting col.slug on "-" and
-- checking sort_order contiguity. This migration:
--   1. creates gradebook_column_groups and gradebook_columns.group_id
--   2. adds RLS consistent with gradebook_columns
--   3. backfills every existing gradebook, first reproducing the heuristic exactly
--      (Phase A), then applying named, separately-labeled fixes (Phase B).
-- After this runs, nothing reads a slug to decide grouping.

------------------------------------------------------------------------------
-- 1. SCHEMA
------------------------------------------------------------------------------

-- id is already the PK, so (id, class_id) is trivially unique. Declaring it lets
-- a group reference its gradebook AND class as a pair, so the two can't disagree.
alter table public.gradebooks
  add constraint gradebooks_id_class_id_key unique (id, class_id);

create table public.gradebook_column_groups (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  class_id bigint not null,
  gradebook_id bigint not null,
  name text not null,
  constraint gradebook_column_groups_name_not_blank check (btrim(name) <> ''),
  -- a group's class_id (what RLS checks) must be its gradebook's class
  constraint gradebook_column_groups_gradebook_fkey
    foreign key (gradebook_id, class_id)
    references public.gradebooks (id, class_id) on delete cascade,
  -- target for the composite FK from gradebook_columns below
  constraint gradebook_column_groups_id_gradebook_key unique (id, gradebook_id),
  -- a name identifies a group within a gradebook (collapse state is keyed by it)
  constraint gradebook_column_groups_gradebook_name_key unique (gradebook_id, name)
);

comment on table public.gradebook_column_groups is
  'Named groups of gradebook columns, shown as collapsible headers. A column is in at most one group (gradebook_columns.group_id). Display position of a group is the position of its lowest-sort_order member.';

-- Membership lives on the column: at most one group per column, by construction.
-- Composite FK: a column can only join a group in its OWN gradebook.
-- ON DELETE SET NULL (group_id): deleting a group ungroups its columns and leaves
-- gradebook_id alone (plain SET NULL would try to null gradebook_id too, which is NOT NULL).
alter table public.gradebook_columns
  add column group_id bigint,
  add constraint gradebook_columns_group_fkey
    foreign key (group_id, gradebook_id)
    references public.gradebook_column_groups (id, gradebook_id)
    on delete set null (group_id);

comment on column public.gradebook_columns.group_id is
  'Group this column is displayed under. NULL = ungrouped (renders as a standalone column).';

create index gradebook_columns_group_id_idx on public.gradebook_columns (group_id);
create index gradebook_column_groups_class_id_idx on public.gradebook_column_groups (class_id);

------------------------------------------------------------------------------
-- 2. RLS  (mirrors "instructors CRUD" / "everyone in class can view" on gradebook_columns)
------------------------------------------------------------------------------

alter table public.gradebook_column_groups enable row level security;

-- Explicit rather than relying on Supabase's default privileges; RLS still decides rows.
grant select, insert, update, delete on table public.gradebook_column_groups to authenticated;

create policy "instructors CRUD"
on public.gradebook_column_groups
as permissive
for all
to authenticated
using (public.authorizeforclassinstructor(class_id))
with check (public.authorizeforclassinstructor(class_id));

-- The EXISTS subquery runs under gradebook_columns' own RLS for the caller, so a
-- student only sees a group if they can see at least one of its columns. A group
-- whose only members are unreleased instructor-only columns stays invisible, and
-- its name can't leak. Staff see every column, so they see every non-empty group.
create policy "class members view groups with a visible column"
on public.gradebook_column_groups
as permissive
for select
to authenticated
using (
  public.authorizeforclass(class_id)
  and exists (
    select 1
    from public.gradebook_columns gc
    where gc.group_id = gradebook_column_groups.id
  )
);

------------------------------------------------------------------------------
-- 3. BACKFILL
--
-- The backfill is a function, not inline SQL, because it has two callers:
--   * this migration, for every gradebook that exists when it runs (production), and
--   * scripts that create a gradebook "as if it predated this migration" (the cs4535
--     seed; CI seeds after migrating, so without this the seeded class is never grouped).
-- It only ever touches columns whose group_id is NULL and never regroups a column,
-- so calling it again is safe and never undoes an instructor's choice.
--
-- Slugs are read here, once per insert, to place a column; the result is stored in
-- group_id. Nothing parses a slug at render time, and a column that already has a
-- group is never moved by this function.
--
-- Two callers keep new columns grouped (section 4): an AFTER INSERT trigger places
-- every newly inserted column (a column that lands directly beside a column of the same
-- family joins that group; a new run of two or more forms a group).
--
-- Policy for rows that don't fit: a column that ends up in a run of one stays ungrouped.
-- That is also how it renders today: the table draws a one-column "group" with no header.
--
-- Deliberate departures from the old groupedColumns heuristic (each also in the PR):
--   FIX 1  a hole in sort_order (a deleted column) no longer splits a group; runs are
--          judged by position in the ordered list, not by sort_order + 1
--   FIX 2  group names come from the columns' own names (longest shared word prefix),
--          not slug fragments: "AI Usage Log", not "Ai"; slug-derived name is the fallback
--   FIX 3  two groups can no longer share a name in one gradebook (collapse state is keyed
--          by name, so same-named groups collapsed together); later ones get " (2)", ...
--   FIX 4  adjacent ungrouped columns computed from exactly the same inputs
--          (dependencies.gradebook_columns) are grouped, e.g. the three expectation totals
------------------------------------------------------------------------------

create or replace function public.gradebook_column_groups_backfill(p_gradebook_id bigint default null)
returns integer
language plpgsql
set search_path = public, pg_temp
as $fn$
declare
  v_created integer := 0;
  v_rows integer;
begin
  drop table if exists _gcg_runs;
  drop table if exists _gcg_dep_runs;

  -- JOIN: an ungrouped column directly beside a grouped column of the same family (same
  -- slug base, or computed from exactly the same columns) joins that group. This is what
  -- places a column inserted next to an existing group. The left neighbour wins a tie.
  with ordered as (
    select
      c.id, c.gradebook_id, c.group_id,
      coalesce(c.sort_order, 0) as so,
      case
        when split_part(c.slug, '-', 1) = 'assignment'
         and cardinality(string_to_array(c.slug, '-')) >= 3
          then 'assignment-' || split_part(c.slug, '-', 2)
        else coalesce(nullif(split_part(c.slug, '-', 1), ''), 'other')
      end as base,
      case
        when jsonb_typeof(c.dependencies -> 'gradebook_columns') = 'array'
         and jsonb_array_length(c.dependencies -> 'gradebook_columns') > 0
        then (select jsonb_agg(x order by x) from jsonb_array_elements(c.dependencies -> 'gradebook_columns') x)
      end as deps
    from public.gradebook_columns c
    where p_gradebook_id is null or c.gradebook_id = p_gradebook_id
  ),
  nb as (
    select
      o.id, o.group_id,
      case
        when lag(o.group_id) over w is not null
         and (lag(o.base) over w = o.base or (o.deps is not null and lag(o.deps) over w = o.deps))
          then lag(o.group_id) over w
        when lead(o.group_id) over w is not null
         and (lead(o.base) over w = o.base or (o.deps is not null and lead(o.deps) over w = o.deps))
          then lead(o.group_id) over w
      end as join_group
    from ordered o
    window w as (partition by o.gradebook_id order by o.so, o.id)
  )
  update public.gradebook_columns gc
  set group_id = nb.join_group
  from nb
  where gc.id = nb.id and gc.group_id is null and nb.join_group is not null;

  -- Runs of same-family, ungrouped columns, by position within each gradebook.
  create temp table _gcg_runs on commit drop as
  with ordered as (
    select
      c.id,
      c.gradebook_id,
      c.class_id,
      c.name,
      c.group_id,
      coalesce(c.sort_order, 0) as so,
      case
        when split_part(c.slug, '-', 1) = 'assignment'
         and cardinality(string_to_array(c.slug, '-')) >= 3
          then 'assignment-' || split_part(c.slug, '-', 2)
        else coalesce(nullif(split_part(c.slug, '-', 1), ''), 'other')
      end as base
    from public.gradebook_columns c
    where p_gradebook_id is null or c.gradebook_id = p_gradebook_id
  ),
  flagged as (
    select
      o.*,
      -- FIX 1: no "sort_order = previous + 1" test; neighbours in the ordered list are
      -- neighbours on screen, whatever holes sit between their sort_orders.
      -- A column that already has a group always breaks a run (never regrouped).
      case
        when lag(o.base) over w is distinct from o.base
          or lag(o.group_id) over w is not null
          or o.group_id is not null
        then 1 else 0
      end as starts_new
    from ordered o
    window w as (partition by o.gradebook_id order by o.so, o.id)
  ),
  islands as (
    select f.*, sum(f.starts_new) over (partition by f.gradebook_id order by f.so, f.id) as island
    from flagged f
  ),
  runs as (
    select
      gradebook_id,
      class_id,
      island,
      base,
      min(so) as first_so,
      array_agg(id order by so, id) as col_ids,
      array_agg(name order by so, id) as names
    from islands
    group by gradebook_id, class_id, island, base
    having count(*) >= 2 and bool_and(group_id is null)
  ),
  named as (
    select
      r.*,
      -- FIX 2: longest word prefix shared by every member's name, minus trailing
      -- punctuation ("Skill #1".."Skill #12" -> "Skill", "AI Usage Log 1/2" -> "AI Usage Log")
      nullif(btrim(regexp_replace(
        array_to_string(
          (string_to_array(r.names[1], ' '))[1:(
            select max(k)
            from generate_series(0, cardinality(string_to_array(r.names[1], ' '))) k
            where (
              select count(distinct array_to_string((string_to_array(n, ' '))[1:k], ' '))
              from unnest(r.names) n
            ) = 1
          )],
          ' '
        ),
        '[[:space:][:punct:]]+$', ''
      )), '') as shared_name,
      -- the old heuristic's name, kept only as a fallback
      case
        when r.base = 'other' then 'Other'
        when r.base like 'assignment-%' then
          upper(left(split_part(r.base, '-', 2), 1)) || substr(split_part(r.base, '-', 2), 2)
        else upper(left(r.base, 1)) || substr(r.base, 2)
      end as slug_name
    from runs r
  ),
  ranked as (
    select
      n.*,
      coalesce(n.shared_name, n.slug_name) as display_name,
      row_number() over (
        partition by n.gradebook_id, coalesce(n.shared_name, n.slug_name)
        order by n.first_so
      ) as name_rank
    from named n
  )
  select
    rk.gradebook_id,
    rk.class_id,
    rk.col_ids,
    -- FIX 3: unique within the gradebook, counting groups that already exist
    rk.display_name || case
      when rk.name_rank + ex.taken > 1 then ' (' || (rk.name_rank + ex.taken) || ')'
      else ''
    end as final_name
  from ranked rk
  cross join lateral (
    select count(*)::int as taken
    from public.gradebook_column_groups g
    where g.gradebook_id = rk.gradebook_id
      and (g.name = rk.display_name or g.name like rk.display_name || ' (%)')
  ) ex;

  insert into public.gradebook_column_groups (class_id, gradebook_id, name)
  select class_id, gradebook_id, final_name from _gcg_runs;
  get diagnostics v_rows = row_count;
  v_created := v_created + v_rows;

  -- Sound only because (gradebook_id, name) is unique.
  update public.gradebook_columns gc
  set group_id = g.id
  from _gcg_runs r
  join public.gradebook_column_groups g
    on g.gradebook_id = r.gradebook_id and g.name = r.final_name
  where gc.id = any (r.col_ids) and gc.group_id is null;

  -- FIX 4: still-ungrouped, adjacent columns computed from the same set of columns.
  -- Structural signal (dependencies), not the slug. A derived column that is not adjacent
  -- to its siblings (e.g. midterm-standing) stays ungrouped rather than being moved.
  create temp table _gcg_dep_runs on commit drop as
  with ordered as (
    select
      c.id, c.gradebook_id, c.class_id, c.group_id,
      coalesce(c.sort_order, 0) as so,
      case
        when jsonb_typeof(c.dependencies -> 'gradebook_columns') = 'array'
         and jsonb_array_length(c.dependencies -> 'gradebook_columns') > 0
        then (select jsonb_agg(x order by x) from jsonb_array_elements(c.dependencies -> 'gradebook_columns') x)
      end as deps
    from public.gradebook_columns c
    where p_gradebook_id is null or c.gradebook_id = p_gradebook_id
  ),
  flagged as (
    select
      o.*,
      case
        when o.deps is null or o.group_id is not null
          or lag(o.deps) over w is distinct from o.deps
          or lag(o.group_id) over w is not null
        then 1 else 0
      end as starts_new
    from ordered o
    window w as (partition by o.gradebook_id order by o.so, o.id)
  ),
  islands as (
    select f.*, sum(f.starts_new) over (partition by f.gradebook_id order by f.so, f.id) as island
    from flagged f
  )
  select
    i.gradebook_id,
    i.class_id,
    min(i.so) as first_so,
    array_agg(i.id order by i.so, i.id) as col_ids,
    coalesce(
      (
        select g.name
        from public.gradebook_columns d
        join public.gradebook_column_groups g on g.id = d.group_id
        where d.id = (min(i.deps::text)::jsonb ->> 0)::bigint
      ),
      'Computed'
    ) || ' totals' as final_name
  from islands i
  where i.deps is not null and i.group_id is null
  group by i.gradebook_id, i.class_id, i.island
  having count(*) >= 2;

  -- A name already taken is skipped (columns stay ungrouped) rather than merged into
  -- an unrelated group; only groups created here receive members.
  with created as (
    insert into public.gradebook_column_groups (class_id, gradebook_id, name)
    select distinct on (gradebook_id, final_name) class_id, gradebook_id, final_name
    from _gcg_dep_runs
    order by gradebook_id, final_name, first_so
    on conflict (gradebook_id, name) do nothing
    returning id, gradebook_id, name
  ),
  assigned as (
    update public.gradebook_columns gc
    set group_id = created.id
    from _gcg_dep_runs r
    join created on created.gradebook_id = r.gradebook_id and created.name = r.final_name
    where gc.id = any (r.col_ids) and gc.group_id is null
    returning gc.id
  )
  select count(distinct created.id) into v_rows from created;
  v_created := v_created + v_rows;

  drop table if exists _gcg_runs;
  drop table if exists _gcg_dep_runs;
  return v_created;
end;
$fn$;

comment on function public.gradebook_column_groups_backfill(bigint) is
  'Groups ungrouped columns of one gradebook (or all, when NULL) the way the pre-migration heuristic did, with the fixes listed in migration 20260924..._gradebook_column_groups. Never regroups a column. Returns the number of groups created.';

-- Not an instructor-facing RPC: only migrations and admin scripts may run it.
revoke all on function public.gradebook_column_groups_backfill(bigint) from public, anon, authenticated;
grant execute on function public.gradebook_column_groups_backfill(bigint) to service_role;

------------------------------------------------------------------------------
-- 4. KEEP NEW COLUMNS GROUPED
-- Without this, every column created after the migration (every new assignment, every
-- new course) would arrive ungrouped and the gradebook would lose all its headers.
-- Statement-level, so a bulk insert places its columns in one pass. SECURITY DEFINER
-- because instructors and the assignment trigger insert columns but may not execute the
-- backfill directly; it only ever touches the gradebooks the statement inserted into.
------------------------------------------------------------------------------

create or replace function public.gradebook_columns_place_new_columns()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $fn$
declare
  v_gradebook_id bigint;
begin
  for v_gradebook_id in select distinct gradebook_id from new_columns loop
    perform public.gradebook_column_groups_backfill(v_gradebook_id);
  end loop;
  return null;
end;
$fn$;

revoke all on function public.gradebook_columns_place_new_columns() from public, anon, authenticated;

create trigger gradebook_columns_place_new_columns
after insert on public.gradebook_columns
referencing new table as new_columns
for each statement
execute function public.gradebook_columns_place_new_columns();

-- Every gradebook that exists right now comes out of this migration grouped.
select public.gradebook_column_groups_backfill();
